CREATE TABLE IF NOT EXISTS "USER" (
  USER_ID INT NOT NULL,
  GRADUATE_ID INT NOT NULL,
  NAME    VARCHAR(60) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  ROLE     VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS "LECTURER" (
  USER_ID INT NOT NULL,
  DEGREE VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "GRADUATE" (
  GRADUATE_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  LECTURER_ID INT NOT NULL,
  GRADUATE_NAME VARCHAR(60) NOT NULL,
  GRADUATE_SCORE VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "GROUP" (
  GROUP_ID INT NOT NULL,
  GROUP_NAME VARCHAR(60) NOT NULL,
  AMOUNT_OF_STUDENTS INT NOT NULL,
  GROUP_YEAR INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "LESSON" (
  LESSON_ID INT NOT NULL,
  LECTURER_ID INT NOT NULL,
  LESSON_NAME VARCHAR(60) NOT NULL,
  LESSON_TIME VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "USERS_IN_GROUPS" (
  GROUP_ID INT NOT NULL,
  USER_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS "LESSONS_FOR_GROUPS" (
  LESSON_ID INT NOT NULL,
  GROUP_ID INT NOT NULL
);